name: Example Workflow
on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Print env and secret
        run: |
          key="ABC"
          upper_prop="SECRET_SOME"
          echo "Secret via env: ${!upper_prop}"  # indirect reference
          echo $ABC
