name: Example Workflow
on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Print all env vars
        run: |
          touch .env
          key="ABC"
          echo $vars
          
          echo "$key=$(echo "$VARS" | jq -r ".$key")" > .env
          cat .env

        env:
          VARS: ${{ toJSON(vars) }}

